/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPromotionsRouteRouteImport } from './routes/_auth/promotions/route'
import { Route as AuthInvoicesRouteRouteImport } from './routes/_auth/invoices/route'
import { Route as AuthReportsIndexRouteImport } from './routes/_auth/reports/index'
import { Route as AuthPromotionsIndexRouteImport } from './routes/_auth/promotions/index'
import { Route as AuthMonitoringIndexRouteImport } from './routes/_auth/monitoring/index'
import { Route as AuthInvoicesIndexRouteImport } from './routes/_auth/invoices/index'
import { Route as AuthRegistrationNewRouteImport } from './routes/_auth/registration/new'
import { Route as AuthInvoicesNewRouteImport } from './routes/_auth/invoices/new'
import { Route as AuthRegistrationRecordsIndexRouteImport } from './routes/_auth/registration/records/index'
import { Route as AuthInvoicesIdIndexRouteImport } from './routes/_auth/invoices/$id/index'
import { Route as AuthInvoicesReturnIdRouteImport } from './routes/_auth/invoices/return/$id'
import { Route as AuthInvoicesReturnNewIdRouteImport } from './routes/_auth/invoices/return/new/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPromotionsRouteRoute = AuthPromotionsRouteRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInvoicesRouteRoute = AuthInvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReportsIndexRoute = AuthReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPromotionsIndexRoute = AuthPromotionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPromotionsRouteRoute,
} as any)
const AuthMonitoringIndexRoute = AuthMonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInvoicesIndexRoute = AuthInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthInvoicesRouteRoute,
} as any)
const AuthRegistrationNewRoute = AuthRegistrationNewRouteImport.update({
  id: '/registration/new',
  path: '/registration/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInvoicesNewRoute = AuthInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthInvoicesRouteRoute,
} as any)
const AuthRegistrationRecordsIndexRoute =
  AuthRegistrationRecordsIndexRouteImport.update({
    id: '/registration/records/',
    path: '/registration/records/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthInvoicesIdIndexRoute = AuthInvoicesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AuthInvoicesRouteRoute,
} as any)
const AuthInvoicesReturnIdRoute = AuthInvoicesReturnIdRouteImport.update({
  id: '/return/$id',
  path: '/return/$id',
  getParentRoute: () => AuthInvoicesRouteRoute,
} as any)
const AuthInvoicesReturnNewIdRoute = AuthInvoicesReturnNewIdRouteImport.update({
  id: '/return/new/$id',
  path: '/return/new/$id',
  getParentRoute: () => AuthInvoicesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/invoices': typeof AuthInvoicesRouteRouteWithChildren
  '/promotions': typeof AuthPromotionsRouteRouteWithChildren
  '/invoices/new': typeof AuthInvoicesNewRoute
  '/registration/new': typeof AuthRegistrationNewRoute
  '/invoices/': typeof AuthInvoicesIndexRoute
  '/monitoring': typeof AuthMonitoringIndexRoute
  '/promotions/': typeof AuthPromotionsIndexRoute
  '/reports': typeof AuthReportsIndexRoute
  '/invoices/return/$id': typeof AuthInvoicesReturnIdRoute
  '/invoices/$id': typeof AuthInvoicesIdIndexRoute
  '/registration/records': typeof AuthRegistrationRecordsIndexRoute
  '/invoices/return/new/$id': typeof AuthInvoicesReturnNewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/invoices/new': typeof AuthInvoicesNewRoute
  '/registration/new': typeof AuthRegistrationNewRoute
  '/invoices': typeof AuthInvoicesIndexRoute
  '/monitoring': typeof AuthMonitoringIndexRoute
  '/promotions': typeof AuthPromotionsIndexRoute
  '/reports': typeof AuthReportsIndexRoute
  '/invoices/return/$id': typeof AuthInvoicesReturnIdRoute
  '/invoices/$id': typeof AuthInvoicesIdIndexRoute
  '/registration/records': typeof AuthRegistrationRecordsIndexRoute
  '/invoices/return/new/$id': typeof AuthInvoicesReturnNewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/invoices': typeof AuthInvoicesRouteRouteWithChildren
  '/_auth/promotions': typeof AuthPromotionsRouteRouteWithChildren
  '/_auth/invoices/new': typeof AuthInvoicesNewRoute
  '/_auth/registration/new': typeof AuthRegistrationNewRoute
  '/_auth/invoices/': typeof AuthInvoicesIndexRoute
  '/_auth/monitoring/': typeof AuthMonitoringIndexRoute
  '/_auth/promotions/': typeof AuthPromotionsIndexRoute
  '/_auth/reports/': typeof AuthReportsIndexRoute
  '/_auth/invoices/return/$id': typeof AuthInvoicesReturnIdRoute
  '/_auth/invoices/$id/': typeof AuthInvoicesIdIndexRoute
  '/_auth/registration/records/': typeof AuthRegistrationRecordsIndexRoute
  '/_auth/invoices/return/new/$id': typeof AuthInvoicesReturnNewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/invoices'
    | '/promotions'
    | '/invoices/new'
    | '/registration/new'
    | '/invoices/'
    | '/monitoring'
    | '/promotions/'
    | '/reports'
    | '/invoices/return/$id'
    | '/invoices/$id'
    | '/registration/records'
    | '/invoices/return/new/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/invoices/new'
    | '/registration/new'
    | '/invoices'
    | '/monitoring'
    | '/promotions'
    | '/reports'
    | '/invoices/return/$id'
    | '/invoices/$id'
    | '/registration/records'
    | '/invoices/return/new/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/invoices'
    | '/_auth/promotions'
    | '/_auth/invoices/new'
    | '/_auth/registration/new'
    | '/_auth/invoices/'
    | '/_auth/monitoring/'
    | '/_auth/promotions/'
    | '/_auth/reports/'
    | '/_auth/invoices/return/$id'
    | '/_auth/invoices/$id/'
    | '/_auth/registration/records/'
    | '/_auth/invoices/return/new/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/promotions': {
      id: '/_auth/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthPromotionsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invoices': {
      id: '/_auth/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthInvoicesRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reports/': {
      id: '/_auth/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/promotions/': {
      id: '/_auth/promotions/'
      path: '/'
      fullPath: '/promotions/'
      preLoaderRoute: typeof AuthPromotionsIndexRouteImport
      parentRoute: typeof AuthPromotionsRouteRoute
    }
    '/_auth/monitoring/': {
      id: '/_auth/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthMonitoringIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invoices/': {
      id: '/_auth/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthInvoicesIndexRouteImport
      parentRoute: typeof AuthInvoicesRouteRoute
    }
    '/_auth/registration/new': {
      id: '/_auth/registration/new'
      path: '/registration/new'
      fullPath: '/registration/new'
      preLoaderRoute: typeof AuthRegistrationNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invoices/new': {
      id: '/_auth/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthInvoicesNewRouteImport
      parentRoute: typeof AuthInvoicesRouteRoute
    }
    '/_auth/registration/records/': {
      id: '/_auth/registration/records/'
      path: '/registration/records'
      fullPath: '/registration/records'
      preLoaderRoute: typeof AuthRegistrationRecordsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invoices/$id/': {
      id: '/_auth/invoices/$id/'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthInvoicesIdIndexRouteImport
      parentRoute: typeof AuthInvoicesRouteRoute
    }
    '/_auth/invoices/return/$id': {
      id: '/_auth/invoices/return/$id'
      path: '/return/$id'
      fullPath: '/invoices/return/$id'
      preLoaderRoute: typeof AuthInvoicesReturnIdRouteImport
      parentRoute: typeof AuthInvoicesRouteRoute
    }
    '/_auth/invoices/return/new/$id': {
      id: '/_auth/invoices/return/new/$id'
      path: '/return/new/$id'
      fullPath: '/invoices/return/new/$id'
      preLoaderRoute: typeof AuthInvoicesReturnNewIdRouteImport
      parentRoute: typeof AuthInvoicesRouteRoute
    }
  }
}

interface AuthInvoicesRouteRouteChildren {
  AuthInvoicesNewRoute: typeof AuthInvoicesNewRoute
  AuthInvoicesIndexRoute: typeof AuthInvoicesIndexRoute
  AuthInvoicesReturnIdRoute: typeof AuthInvoicesReturnIdRoute
  AuthInvoicesIdIndexRoute: typeof AuthInvoicesIdIndexRoute
  AuthInvoicesReturnNewIdRoute: typeof AuthInvoicesReturnNewIdRoute
}

const AuthInvoicesRouteRouteChildren: AuthInvoicesRouteRouteChildren = {
  AuthInvoicesNewRoute: AuthInvoicesNewRoute,
  AuthInvoicesIndexRoute: AuthInvoicesIndexRoute,
  AuthInvoicesReturnIdRoute: AuthInvoicesReturnIdRoute,
  AuthInvoicesIdIndexRoute: AuthInvoicesIdIndexRoute,
  AuthInvoicesReturnNewIdRoute: AuthInvoicesReturnNewIdRoute,
}

const AuthInvoicesRouteRouteWithChildren =
  AuthInvoicesRouteRoute._addFileChildren(AuthInvoicesRouteRouteChildren)

interface AuthPromotionsRouteRouteChildren {
  AuthPromotionsIndexRoute: typeof AuthPromotionsIndexRoute
}

const AuthPromotionsRouteRouteChildren: AuthPromotionsRouteRouteChildren = {
  AuthPromotionsIndexRoute: AuthPromotionsIndexRoute,
}

const AuthPromotionsRouteRouteWithChildren =
  AuthPromotionsRouteRoute._addFileChildren(AuthPromotionsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthInvoicesRouteRoute: typeof AuthInvoicesRouteRouteWithChildren
  AuthPromotionsRouteRoute: typeof AuthPromotionsRouteRouteWithChildren
  AuthRegistrationNewRoute: typeof AuthRegistrationNewRoute
  AuthMonitoringIndexRoute: typeof AuthMonitoringIndexRoute
  AuthReportsIndexRoute: typeof AuthReportsIndexRoute
  AuthRegistrationRecordsIndexRoute: typeof AuthRegistrationRecordsIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthInvoicesRouteRoute: AuthInvoicesRouteRouteWithChildren,
  AuthPromotionsRouteRoute: AuthPromotionsRouteRouteWithChildren,
  AuthRegistrationNewRoute: AuthRegistrationNewRoute,
  AuthMonitoringIndexRoute: AuthMonitoringIndexRoute,
  AuthReportsIndexRoute: AuthReportsIndexRoute,
  AuthRegistrationRecordsIndexRoute: AuthRegistrationRecordsIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
